config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'users#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :messages
  resources :user_rooms
  resources :settings
  resources :notifications
  mount Sidekiq::Web => '/sidekiq'
  # resources :users 
  resources :rooms do 
    get :user, on: :member
    resources :users
    resources :messages
    # get :user, on: :member , as: :room_user
  end
  mount ActionCable.server => '/room_channel'
#  get '/search_messages' => 'messages#search_messages', as: :search_messages
  #get '/all_members/:id' => 'rooms#all_members_in_room', as: :all_members
  #post '/add_user' => 'rooms#update'
  #post '/add_user' => 'users#add_user_to_room'
  #post '/send_message'=> 'messages#create'
  #get '/show_room' => 'messages#show_room_messages'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :room
	belongs_to :user
	has_many_attached :images
	scope :search_messages, ->(room_id,text) { Room.find_by_id(room_id).messages.where("description LIKE ?", "%#{text}%") }
	validates :description, presence:true

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :set_notification , only: %i[ create ]

  # GET /messages or /messages.json
  def index
   @messages = Message.all
   @room = Room.find_by(id: params[:room_id])
   @user= current_user
    if params[:search_by_messages] && params[:search_by_messages] != ""
      @search_messages = Message.search_messages(@room.id, params[:search_by_messages])
    end
    if @search_messages == nil
      @notice = "message not found"
    end    
 # end
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @my_room = params[:room]
    @user = params[:user]
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @room = message_params[:room_id]
    @message.save
    if message_params[:images].present?
      @message.images = message_params[:images]
    end
    
    respond_to do |format|
      if @message.save 
       #format.html { redirect_to room_url(@room), notice: "Message was successfully created." }
       #format.json { render :show, status: :created, location: @message }       
       #SendMessageJob.perform_later(@message.id)
       ActionCable.server.broadcast "chat_#{@message.room_id}", message: @message
       #ChatChannel.broadcast_to("chat", { body: "This Room is Best Room." })
       format.js{}
      # format.js {redirect_to "/rooms/#{@room}?format=js&message_id=#{@message.id}" , notice: "Message was successfully created.",message: @message }
      else
       # format.html { redirect_to room_url(@room) , notice: "Message not created" }
        #format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def search_messages
    @room = Room.find_by(id: params[:room_id])
    if params[:search_by_messages] && params[:search_by_messages] != ""
      @search_messages = Message.new.search_messages(@room.id, params[:search_by_messages])
    end

    if @search_messages == nil
      @notice = "message not found"
    end  
  end


  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @room = Room.find_by(id: params[:room_id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to room_url(@room), notice: "Message was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:description,:attachment, :room_id , :user_id , images: [])
    end
    def set_notification
      @notification = Notification.create(user_id: params[:message][:user_id], sender_id: params[:message][:sender_id], room_id: params[:message][:room_id], seen_by: params[:message][:sender_id] )
      @notification.save
      View.create(user_id: @notification.user_id , notification_id: @notification.id , viewed_by: @notification.user_id)
    end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message, remote: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>      
    </div>
  <% end %>
  
  <div class="actions">
    <ul>      
      <%= form.label :description, 'Type Message Below ', class:"description ", style: 'font-weight: normal;' %>
      <%= form.text_field :description, class: 'form-control' %>
      
      <%= form.file_field :images,multiple: true, direct_upload: 'false' %>
      <%= form.text_field :user_id, value: current_user.id,  class: 'hidden_field' %> 
      <%= form.text_field :sender_id, value: current_user.id,  class: 'hidden_field' %> 
      <%= form.text_field :room_id, value: room_id,  class: 'hidden_field' %></br>
      <%= form.submit value:"Send Message", class: "btn btn-primary send_message" %>
    </ul>        
  </div>
<% end %>

<Style>
  .hidden_field{
    display: none;
  }
  .new_message{
    color: :red;
  }
  .form-control{
    width: 92%;
  }
  @media only screen and (max-width: 469px)  {
.form-control{
    width: 80%;
    margin-left: 10px;
  }
  .description{
    margin-left: 10px;
  }
  .send_message{
    margin-left: 10px;
  }
  }
</Style>

app/views/messages/create.js.erb
alert("i m createjs")
console.log("I m createjs")
$('#message').prepend("<tr><td><p><%=User.find_by_id(@message.user_id).email%></p></td><td><p>:</p></td><td><p><%=@message.description%></p></td><td><%=@message.created_at.time.in_time_zone('Pacific Time (US & Canada)')%></td></tr>")

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<!--<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Message', new_message_path %> -->






<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>
 <div class=" d-flex flex-row justify-content-center" >
  <div class=" " >
  <h1 class=" text-danger"> Below are searched messages in <%= @room.name %> : </h1>
    <% if @search_messages.present? %>
       <% @search_messages.each do |search_message| %>
       <table>
         <tr>
         <% if search_message.user_id.present? && search_message.user_id != 0 %>
         <%=  User.find_by_id(search_message.user_id).email %>
         <% end %> 
          : 
         <%= search_message.description %>
         </tr>
       </table>
      <%end%>
      <%else%>
      <%= @notice %>
      <%end%>
 </div>
<style>
.hidden_field{
    display: none !important;
  }
</style>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/search_messages.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>
 <div class=" d-flex flex-row justify-content-center" >
  <div class=" " >
  <h1 class=" text-danger"> Below are searched messages in <%= @room.name %> : </h1>
    <% if @search_messages.present? %>
       <% @search_messages.each do |search_message| %>
       <table>
         <tr>
         <% if search_message.sender_id.present? && search_message.sender_id != 0 %>
         <%=  User.find_by_id(search_message.sender_id).email %>
         <% end %> 
          : 
         <%= search_message.description %>
         </tr>
       </table>
      <%end%>
      <%else%>
      <%= @notice %>
      <%end%>
 </div>
<style>
.hidden_field{
    display: none !important;
  }
</style>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>
<p>ttt</p>
<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/messages/show_room_messages.erb
<h1>Wellcome to the room:
 <%= @room.name%></h1>

 <h1> messages: </h1>
   <% @room_messages.each do |room_message| %>
   <table>
	   <tr>
	   
	   <%= User.find_by_id(room_message.user_id).name %>  : 
	   <%= room_message.description %>

	   </tr>
   </table>
   <%end%> 