config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'users#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :messages
  resources :user_rooms
  resources :settings
  resources :notifications
  mount Sidekiq::Web => '/sidekiq'
  # resources :users 
  resources :rooms do 
    get :user, on: :member
    resources :users
    resources :messages
    # get :user, on: :member , as: :room_user
  end
  mount ActionCable.server => '/room_channel'
#  get '/search_messages' => 'messages#search_messages', as: :search_messages
  #get '/all_members/:id' => 'rooms#all_members_in_room', as: :all_members
  #post '/add_user' => 'rooms#update'
  #post '/add_user' => 'users#add_user_to_room'
  #post '/send_message'=> 'messages#create'
  #get '/show_room' => 'messages#show_room_messages'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :user_rooms
	has_many :rooms, through: :user_rooms
  has_many :messages
  mount_uploader :avatar, AvatarUploader
  validates :email, presence:true
  #has_many :notifications


  has_many :views
  has_many :notifications, through: :views
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
     super
     UserMailer.welcome_email(current_user.id).deliver_now
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
  #  params.require(:user).permit(:email, :password, :password_confirmation, :birthday)
     devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :birthday])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    if params[:room_id].present?
      @room = Room.find_by(id: params[:room_id])
      @room_members = @room.users.all
    end
     #render js: "alert('The username to be displayed is: #{params[:name]}')"
   # render js: "alert('The username to be displayed is: #{params[:email]}')"
  end

  # GET /users/1 or /users/1.json
  def show
    @room = Room.all
    @my_rooms =User.find_by(id: params[:id]).rooms.all
  end
  def add_user_to_room
    @room = Room.find_by(name: params[:room_name]) 
    @user =  User.find_by(id: params[:user_id])
    if @room.user_ids.include? @user.id
       @message="user is already present" 
    else
      @room.users << @user
    end
    #@room.users.create(@user
    #@room.users.create(name: @user.name, number: @user.number)
    @room.save
    redirect_to user_path(@user)         
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_birthday
    
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :number, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
<h1>enter details of user :</h1>
 <div class="input-field-group">
    <%= form.text_field :name, placeholder: 'Name', class: 'form-control' %>
  </div>
  <div class="input-field-group">
    <%= form.text_field :number, placeholder: 'Number', class: 'form-control' %>
  </div>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
     
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<% if @room.present? %>
<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>
 <div class=" d-flex flex-row justify-content-center" >
  <div class=" " >
  <h1 class=" text-danger"> Below are group memebers in <%= @room.name %> : </h1>
   <% @room_members.each do |room_member| %>
   <table>
     <tr>
     <p> User Email : <%= room_member.email %></p>
     </tr>
   </table>
   <%end%>
</div>
  
 </div>
 <%end%>
<style>
.hidden_field{
    display: none !important;
  }
</style>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<h1>Please Join a group :</h1>
<% @room.each do |room| %> 

<table>
	<tr>
		<td>
		<p> <%= room.name %> </p>	
		</td>
		<td>
		<a class="btn btn-default btn-xs" data-method="patch"  href=<%= room_path(id:room, user_id:@user ) %>> join group </a>	
		</td>
	</tr>
</table>
<% end %>

<h1> My groups : </h1>
<% @my_rooms.each do |my_room| %> 
	<tr>
		<td>
			<p> <%= my_room.name %> </p>	
		</td>
		<td>

			<a class="btn btn-default btn-xs" data-method="get"  href=<%= new_message_path(room:my_room, user:@user )%> > send message </a>	
		</td>
		<td> 
			<a class="btn btn-default btn-xs"  href=<%= messages_path(room:my_room, user:@user )%> > open_group </a>	
		</td>
		
	</tr>	
<% end %>