config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'users#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :messages
  resources :user_rooms
  resources :settings
  resources :notifications
  mount Sidekiq::Web => '/sidekiq'
  # resources :users 
  resources :rooms do 
    get :user, on: :member
    resources :users
    resources :messages
    # get :user, on: :member , as: :room_user
  end
  mount ActionCable.server => '/room_channel'
#  get '/search_messages' => 'messages#search_messages', as: :search_messages
  #get '/all_members/:id' => 'rooms#all_members_in_room', as: :all_members
  #post '/add_user' => 'rooms#update'
  #post '/add_user' => 'users#add_user_to_room'
  #post '/send_message'=> 'messages#create'
  #get '/show_room' => 'messages#show_room_messages'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages
	has_many :user_rooms
	has_many :users, through: :user_rooms
	has_many :notifications
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @room = Room.new
    @rooms = Room.all
    #@count = Notification.where.not(seen_by:current_user.id).group(:room_id).count
    #@notifications = Notification.group(:room_id).count
    #@seen_notifications = Notification.includes(:views).where(views:{user_id:current_user.id}).group(:room_id).count

    #@seen_ids = @room.notifications.includes(:views).where(views:{user_id:current_user.id}).pluck(:id).uniq
    #@notify = @notification_ids -@seen_ids
    @count={}
    @all_notifcations = Notification.group(:room_id).count
    @seen_notifications = Notification.includes(:views).where(views: {user_id:current_user.id}).group(:room_id).count
    @seen_notifications.each do |notify|
      @count[notify[0]] = @all_notifcations[notify[0]] - @seen_notifications[notify[0]]
    end
    #@count =  Notification.includes(:views).where.not(views: {user_id:current_user.id}).group(:room_id).count
    if current_user.present?
      @my_rooms = current_user.rooms.all
    end
  end

  # GET /rooms/1 or /rooms/1.json
  def show
   # @notify = @room.notifications.pluck(:id,:seen_by)
   # @notify.each do |notification|
    #  @room.notifications.find(notification[0]).update!(seen_by: notification[1]+","+current_user.id.to_s)
    #end
      @notification_ids = @room.notifications.pluck(:id)
      @seen_ids = @room.notifications.includes(:views).where(views:{user_id:current_user.id}).pluck(:id).uniq
      @notify = @notification_ids -@seen_ids
      @notify.each do |notification|
        View.create(user_id: current_user.id , notification_id: notification , viewed_by: current_user.id)
      end
    $id = params[:id]
    @room_messages = @room.messages.all
      
    @message = Message.new
   if params[:message_id].present?
    @message_display = Message.find_by(id: params[:message_id])
   end
   # format.html {render :show} 

   if request.format.js? 
    render :show, message_display: @message_display
   end  
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end
  def all_members_in_room
    @room = Room.find_by(id: params[:id])
    @room_members = @room.users.all
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.save
    respond_to do |format|
      if @room.save
        format.js {render :index}
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    if params[:join].present?
        @room = Room.find_by(id: params[:id]) 
      if @room.user_ids.include? current_user.id
         @message="user is already present" 
      else
        @room.users << current_user
      end
        @room.save
        redirect_to room_url(@room) 
    elsif params[:add_member].present? 
      if params[:add_by_email].to_s.empty?
        @message_display = "user connot be empty"
      end  
        @room = Room.find_by(id: params[:id])
        @user = User.find_by(email: params[:add_by_email])
  
      if @user.present?
        if !@user.email.to_s.empty?
          if @room.user_ids.include? @user.id
            @message_display="user is already present" 
          else
            @room.users << @user
            @message_display ="user added successfully" 
          end
        else
          if @message_display.to_s.empty?
          @message_display = "user connot be added"
          end
        end
      else
         @message_display = "user connot be added"
      end        
        @room.save
        redirect_to room_url(@room, message_display: @message_display)            
    else
      respond_to do |format|
        if @room.update(room_params)
          format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
          format.json { render :show, status: :ok, location: @room }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @room.errors, status: :unprocessable_entity }
        end
      end
    end 
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :id, :owner_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room, remote:true) do |form| %>

  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% if current_user.present? %>
    <%= form.text_field :owner_id, value: current_user.id,  class: 'hidden_field' %> 
    <%end%>
  </div>

  <div class="actions">
    
    <%= form.submit value:"Create Group", class: "btn btn-primary send_message" %>
  </div>
<% end %>

<style type="text/css">
  .hidden_field{
    display: none;
  }
</style>

app/views/rooms/all_members_in_room.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>
 <div class=" d-flex flex-row justify-content-center" >
  <div class=" " >
  <h1 class=" text-danger"> Below are group memebers in <%= @room.name %> : </h1>
   <% @room_members.each do |room_member| %>
   <table>
     <tr>
     <p> User Email : <%= room_member.email %></p>
     </tr>
   </table>
   <%end%>
</div>
  
 </div>
<style>
.hidden_field{
    display: none !important;
  }
</style>

app/views/rooms/create.js.erb
alert("i came here");

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>
<div class=" d-flex flex-row justify-content-center background" >
  <div class="inner-div " >
  <h1 class="text-danger">ALL Private Groups:</h1>
  <p class="text-danger">Please Join a Whatsapp Group to start a chat</p>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
     <%= render 'form', room: @room %>
    <%= link_to 'Make New Whatsapp Group', new_room_path %>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <% if room.user_ids.include? current_user.id %>
        
          <td><%= link_to room.name, room %></td>
          <%else%>
          <td><%= room.name %></td>
          <%end%>      
          <td>
             <% if room.user_ids.exclude? current_user.id %>
            <a class="btn btn-default btn-xs" data-method="patch"  href=<%= room_path(id:room, join: "join" ) %>> join group </a>
            <%else%>
           <!-- <p class="text-danger"> Already Joined </p>-->
            <%end%>
          </td>

          <% if @count[room.id] == 0 %>
            <td><p></p></td>
            <%else%>
            <td><p class="notification"><%=@count[room.id]%></p></td>
          <%end%>
        </tr>
      <% end %>
      
    </tbody> 
  </table>
</br>

  <div id="room">
    
  </div> 
  <br>
  


  <!--<h1 class="text-danger"> My JOINED Groups: </h1>
      <% @my_rooms.each do |my_room| %>
       <table>
         <tr>
          <td>
         <%= my_room.name %>
          </td>
          <td><%= link_to 'Open Group', my_room %></td>
         </tr>
       </table>
   <%end%>
 -->
</div>
  
 
</div>
<style>
  a:hover {

}
.background{
 background-color: aliceblue ;
}
.inner-div{
  background-color: #ffc1070d;
}
.link-style{
  font-size: 15px;
  color: black;
  font-weight: 100
}
.notification{
  margin-top: 0;
  margin-bottom: 1rem;
  padding-left: 10px;
  border-radius: 100%;
  background-color: greenyellow;
}
</style>

app/views/rooms/index.js.erb
alert("js working")
$('#room').prepend('<a  href="/rooms/<%=@room.id%>" class="link-style"><%=@room.name%></a>')

app/views/rooms/new.html.erb
<h1>New Whatsapp Group</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<% if @room.owner_id.present? && @room.owner_id == current_user.id %>
<%= link_to 'Edit', edit_room_path(@room) %>
<%end%> 
<%= link_to 'Back', rooms_path %>
 <div class=" d-flex flex-row justify-content-center col-md-12 col-lg-12 col-sm-12 " >

  <div class="col-md-8 col-lg-8 col-sm-8 " >
    <div class="col-md-12 col-lg-12 col-sm-12 " >
    <% if  params[:message_display].present? %>
      <p class="text-success" style="font-size: 20px;"><%=  params[:message_display] %></p> 
    <%end %>

    <h1 class=" text-danger"> Welcome to  <%= @room.name %> messages: </h1>
         <div class=" dropdown-style w3-dropdown-click" >
     <img src="/assets/Filter_Icon.png", style='height:50px;width:50px;float: right;'
      onclick="myFunction()" class=" " >
      <div class="dropdown-content w3-dropdown-content " id="Demo">
      <table class="col-md-12 col-lg-12 col-sm-12 col-xs-12 ">
        <tr class="row">
          <td class=" col-sm-12 col-md-12 col-lg-12 col-xs-12">
            <%= button_to 'ALL MEMBORS', room_users_path(@room), method:  :get, class: 'btn btn-info'  %>
          </td>
          <td class=" col-sm-12 col-md-12 col-lg-12 col-xs-12 ">
            <%= form_tag room_messages_path(@room.id), method: "GET" do %>
             
              <%= text_field_tag :search_by_messages, params[:search_by_messages] , placeholder:"search by messages"%> 
              <%= submit_tag "Search" , class: "btn btn-primary margin" %>
            <% end %>
          </td>
          <td class=" col-sm-12 col-md-12 col-lg-12 col-xs-12">
            <%= form_tag room_path, method: "patch",remote: true do %>
              <%= text_field_tag :id, params[:id] , value:@room.id ,  class: 'hidden_field' %>
              <%= text_field_tag :add_member, params[:add_member] , value:"add_member" ,  class: 'hidden_field' %>
              <%= text_field_tag :add_by_email, params[:add_by_email] , placeholder:"add members by email"%> 
              <%= submit_tag "Add members" , class: "btn btn-primary margin" %>
            <% end %>
          </td>    
        </tr>
    </table>
      </div>
      </div>
    </br>
     <% @room_messages.includes(:user).each do |room_message| %>
      <table>
       
          <% if room_message.user_id.present? && room_message.user_id != 0 %>
            <% if room_message.user_id== current_user.id %>
                 <tr>
              <td style="width:150px">
                </td>
              <td>
                  <%if room_message.images.attached?%>
                    <% if room_message.images.last.content_type =="image/png" || room_message.images.last.content_type =="image/jpeg" || room_message.images.last.content_type =="image/jpg"  %>
                      <%= image_tag room_message.images.last.representation(resize_to_limit: [100, 100]) %>
                    <%end%>
                    <% if room_message.images.last.content_type =="video/mp4" %> 
                      <%= video_tag url_for(room_message.images.last) , controls: true %>
                    <%end%>  
                  <%end%>
               </td>
            </tr>
            <tr>
            <td style="width:150px">
            </td>
            <td style="background-color: lightgreen;">
             
              <%=  room_message.user.email %> online
              : 
              <%= room_message.description %>
            </td>
            <td><%=room_message.created_at.in_time_zone('Pacific Time (US & Canada)')%></td>

            <td><%= link_to 'Delete Message', room_message_path(@room.id,room_message.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
           </br>
           
        </tr>   
          <%else%>
           <tr>     
          <td>
              <%if room_message.images.attached?%>
                <% if room_message.images.last.content_type =="image/png" || room_message.images.last.content_type =="image/jpeg" || room_message.images.last.content_type =="image/jpg"  %>
                  <%= image_tag room_message.images.last.representation(resize_to_limit: [100, 100]) %>
                <%end%>
                <% if room_message.images.last.content_type =="video/mp4" %> 
                  <%= video_tag url_for(room_message.images.last) , controls: true %>
                <%end%>  
              <%end%>
           </td>
           <td style="width:150px">
            </td>
        </tr>
        <tr>
         <tr>
          <td style="background-color: antiquewhite; float: right;">
             <%= room_message.user.email %>
            : 
            <%= room_message.description %>
          </td>
          <td><td><%=room_message.created_at.time.in_time_zone('Pacific Time (US & Canada)') %></td></td>
          <td>
           
            </td>

          <td style="width:150px"></td>
          </br> 
         </tr> 
          <% end %>
       <% end %> 
       </tr>
      
      </table>
    <%end%>
    </br>
    <div >
     <table id="message" style="background-color: lightgreen;margin-left: 148px;">
       
     </table>
     <span class="message-normal">
       <table id="your-message" >       
       </table>
     </span>
    </div>
    
    <%= render partial: 'messages/form', locals: {message: @message, room_id:@room.id}  %>
   
    <p id="notice"><%= notice %></p>
    </div>
  </div>
</div>




<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<script>
function myFunction() {
  var x = document.getElementById("Demo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>


<style>
.hidden_field{
    display: none !important;
  }
  .actions{
    margin-left: -36px;
  }
  input, button, select, optgroup, textarea {
    margin: 0;
    height: 38px;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  padding: 12px 16px;
  z-index: 1;
  margin-top: 52px;
}

 .dropdown-content {
  display: block;
}
@media only screen and (max-width: 469px)  {
.dropdown-style{
  float: right;
  margin-right: 80px;
}
}
.margin{
      margin-top: 8px;
}


.dropbtn {
  background-color: #3498DB;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}
 

@media only screen and (max-width: 410px)  {
 .dropdown-style{
  float: left !important;
 }
}
.msg-#{current_user.id} {
  background: lightgreen ;
}
.background-color{
  background: lightgreen ; 
}
.message-normal{
  background: antiquewhite;
}
</style>
   <script>
    window.scrollTo({ left: 0, top: document.body.scrollHeight, behavior: "smooth" });
    
  function myFunction() {
    var x = document.getElementById("Demo");
    if (x.className.indexOf("w3-show") == -1) { 
      x.className += " w3-show";
    } else {
      x.className = x.className.replace(" w3-show", "");
    }
  }
  
   </script>

app/views/rooms/show.js.erb
$("<%= escape_javascript(render @message_display.description) %>").appendTo("#message");